### ISSUE TITLE
Docker 2.3.0.5 Error

### ISSUE THREAD

**Issue by jasperfurniss** [powerhome/playbook#1093]
**Describe the bug**
Make commands are not working with version 2.3.0.5 of Docker.
The error is happening on this line of code: https://github.com/powerhome/playbook/blob/v6.7.0/docker-compose.yml#L27
If you change the string `'2.0'` to a number `2.0`, the error no longer appears. 

**To Reproduce**
1. Have version 2.3.0.5 of Docker desktop installed.
2. Run `make start` from the root of Playbook.
3. See error

**Expected behavior**
Make commands should work... like `make start` or `make install`.

**Screenshots**
<img width="924" alt="Screen Shot 2020-09-15 at 10 29 02 AM" src="https://user-images.githubusercontent.com/9158723/93231337-a4084c00-f746-11ea-81a7-0f90a6bafb04.png">

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser: Chrome

**Comment by benlangfeld** [comment]
What version of `docker-compose` do you have? Mine:

```
➭ docker-compose -v
docker-compose version 1.26.2, build eefe0d31
```

**Comment by jasperfurniss** [comment]
I already downgraded my docker back down to 2.3.0.4....
BUT I think i had 1.27.2... because that's what version of `docker-compose` is shipped with the latest version of docker.
https://docs.docker.com/docker-for-mac/release-notes/

**Comment by jasperfurniss** [comment]
```
docker-compose -v
docker-compose version 1.27.2, build 18f557f9
```

**Comment by benlangfeld** [comment]
Good:

<img width="872" alt="Screenshot 2020-09-15 at 13 01 43" src="https://user-images.githubusercontent.com/210221/93235252-a9b85e80-f753-11ea-99a2-cec5c1e038ee.png">

Bad:

<img width="872" alt="Screenshot 2020-09-15 at 13 08 51" src="https://user-images.githubusercontent.com/210221/93235945-9d80d100-f754-11ea-947e-45dfe3421bf6.png">

The new version works correctly in nitro-web, so this appears to be limited to playbook. nitro-web [uses the v2 schema](https://github.com/powerhome/nitro-web/blob/master/docker-compose.yml#L1) because of [problems with v3](https://github.com/powerhome/nitro-web/commit/e981a906a3ffd279116af83bc4079b0e6fc38ffc). I recommend you do the same with playbook, because the limits you have in place right now aren't actually doing anything.

**Comment by thestephenmarshall** [comment]
Thanks @benlangfeld we will keep with what `nitro-web` uses for schema version.

**Comment by jasperfurniss** [comment]
Thanks @benlangfeld We will add a ticket to update. Thanks!

**Comment by jasperfurniss** [comment]
We now have an open ticket for this in Runway that we will be tackling soon: https://nitro.powerhrg.com/runway/backlog_items/NUXE-152
