### ISSUE TITLE
React Filter Bar "Results" does not have enough padding on the right side

### ISSUE THREAD

**Issue by kellyeryan** [powerhome/playbook#1230]
#### Screenshot

<img width="928" alt="Screen Shot 2020-12-03 at 4 08 24 PM" src="https://user-images.githubusercontent.com/51907753/101088633-fad13500-3581-11eb-9f8e-e5f9e0d0e961.png">

**Describe the solution you'd like**

I would like there to be more padding to the right of the "Results" on the filter bar.

**Describe alternatives you've considered**

I've spoken with Eva about this edit and she said that this could be done by editing the filter on the kit level.

**Additional context**

This issue is from this story: https://nitro.powerhrg.com/runway/backlog_items/CHPN-90 

I was asked to refine the padding and spacing for several things related to the filter. I was able to accomplish all of them, except add the extra padding on the end of "Results." When I explained this to the evaluator, I was asked to open an issue for this to be fixed in the React Pb Filter kit.

**Comment by jasoncypret** [comment]
@kellyeryan Are you planning to add sorting to the page? If so that will solve your problem. This is the first instance using results without a sort. The kit will need to be updated to tackle this as a new use case.

In the meantime, I suggest using the no background prop with padding to achieve what you are after. Here's a quick example.

```
<Card paddingRight="sm">
  <Filter background={false}>
  ...ect
```

**Comment by jasoncypret** [comment]
Added to backlog https://nitro.powerhrg.com/runway/backlog_items/NUXE-347
