### ISSUE TITLE
Time kit displaying wrong timezone

### ISSUE THREAD

**Issue by eabousaif** [powerhome/playbook#553]
The time kit displays an incorrect timezone in the UI, even after specifying a correct timezone prop. In this instance, a newly created click record was created at 11:07 AM, but it was displayed as 5:07 AM in the UI, even after specifying a timezone prop.

<img width="177" alt="screen-shot-2020-01-10-at-11-34-36-am" src="https://user-images.githubusercontent.com/46111475/72171530-29aa4f80-33a1-11ea-99b1-1f0d4e006702.png">
<img width="266" alt="screen-shot-2020-01-10-at-11-23-21-am" src="https://user-images.githubusercontent.com/46111475/72171535-2adb7c80-33a1-11ea-9716-1d8657f2b492.png">
<img width="355" alt="screen-shot-2020-01-10-at-11-23-55-am" src="https://user-images.githubusercontent.com/46111475/72171537-2c0ca980-33a1-11ea-9c23-17e93375a84b.png">

**Comment by jasperfurniss** [comment]
After some discovery, we determined that this kit simply did not support using :nice_time as a prop value. Ezz was attempting to bridge both worlds a little and it was causing the time to display off by several hours. More investigation, however, could be done (and more team discussion) as to how & when to deprecate the helpers here (https://github.com/powerhome/nitro-web/blob/7691d86a3fd97afed6c43186c01c47c56d1110e7/components/core_models/config/initializers/conversions.rb#L59), in favor of using the new PB Time Kit. I'm closing this issue, since we were able to solve it by simply using the Playbook kit as documented.
